### ISSUE TITLE
Crashes as soon as launched

### ISSUE THREAD

**Issue by hyd00** [cometchat-pro/ios-objective-c-chat-app#1]
Trying running the project. As soon as it is launched on the phone, it crashes without any error message. 

Check attached picture. 

Please help?
<img width="1017" alt="Screenshot 2019-05-24 at 10 21 22 PM" src="https://user-images.githubusercontent.com/15999948/58345718-707b2180-7e72-11e9-8eda-416eafb3cbc2.png">

**Comment by ghost** [comment]
@hyd00 , we are looking into it , will get back to you as soon as issue got fixed .

**Comment by ghost** [comment]
@hyd00  , we have updated UI Sample App for Objc for SDK `CometChatPro` SDK version `1.5.1` , please pull / clone fresh app.

**Comment by hyd00** [comment]
@bhooshanpatil Downloaded project again but Same Issue :(

**Comment by ghost** [comment]
@hyd00, which version of `Xcode` you are using?

**Comment by hyd00** [comment]
@bhooshanpatil Xcode Version 10.2.1

**Comment by ghost** [comment]
@hyd00 , current sample app has complied with `Xcode 10.1`, and that's might be an issue, we are releasing sample App compatible with `Xcode 10.2`.

**Comment by hyd00** [comment]
Sure. By when will you release it?

**Comment by ghost** [comment]
hey @hyd00, you can run the current sample app on `xcode10.2` by removing `vendors` folder from files and by integrating CometChatPro using `cocoa pods`, [HERE](https://bit.ly/2Mm7bUD) is a sampleApp for your reference compatible with `Xcode10.2`

**Comment by hyd00** [comment]
@bhooshanpatil  Kindly please fix and update the repo here so we can run the project easily. Your link doesn't work.

P.s. I cannot find `vendors` folder in the project. Where is it?

**Comment by ghost** [comment]
Hello @hyd00, project complied with Xcode 10.2 doesn't have `vendors` folder as `CometChatPro` is integrated using `CocoaPods`, kindly use `pod update` to get the latest version of `CometChatPro` SDK

**Comment by pushpsenairekar2911** [comment]
Hello @hyd00, We have resolved this issue. Kindly, take the fresh pull of the project and build. hope this helps.
