### ISSUE TITLE
[SDK-1.8.3] Use of undeclared identifier 'CometChat'

### ISSUE THREAD

**Issue by tiny9085** [cometchat-pro/ios-objective-c-chat-app#2]
Hello, guys. Thank for this awesome library. I'm trying to integrate this sdk into my react-native application in order to make wrapper for it and use as regular native module.

I use manual integration steps. I added CometChatPro.framework, JitsiMeet.framework and WebRTC.framework into my project. Added them to Embedded Binaries. Set "Enable Bitcode" to No. Set "Always Embed Swift Standard Libraries" to Yes. Added "$(SDKROOT)/usr/include/libxml2" to my "Header Search Paths".
Application is built successfully until i'm trying to init CometChat as mentioned in the docs.
I make "#import <CometChatPro/CometChatPro-Swift.h>" in my AppDelegate.m. And when i try to call

[[CometChat alloc]initWithAppId:@"4152a64155ab75" onSuccess:^(BOOL isSuccess) {
    
    if (isSuccess) {
      NSLog(@"Successfully init CometChatPro");
    }
    
  } onError:^(CometChatException * error) {
    
    NSLog(@"Error in init %@",[error errorDescription]);
    
  }];
XCode gives me compilation error: "Use of undeclared identifier 'CometChat'"

I see "@interface CometChat : NSObject" inside "CometChatPro.framework/Headers/CometChatPro-Swift.h" file
But it seems XCode can't see it.

Could you please point me what i'm doing wrong?

ios-chat-sdk version 1.8.3
Also tried removing DerivedData and Clean project

Thank you

Update: The same issue if use cocoapods approach. Issue is reproduced only in Objective-c project. Integration in Swift project works well

**Comment by tiny9085** [comment]
this issue even appear SDK 1.9.0

**Comment by jeetkapadia** [comment]
There might be an issue with your cocoa pods version. Please fix it by using below steps:

1. pod deintegrate
2. sudo gem install cocoapods-clean
3. pod clean
4. Open the project and delete the "Pods" folder that should be red.
5. pod setup
6. pod install

**Comment by tiny9085** [comment]
thanks,i followed the steps, but no luck,objective-c sample build failed, the error 'Use of undeclared identifier 'CometChat'' also exist.
Set "Enable Bitcode" to No. Set "Always Embed Swift Standard Libraries" to Yes. Added "$(SDKROOT)/usr/include/libxml2" to my "Header Search Paths".

![image](https://user-images.githubusercontent.com/10555232/63416773-a8bedb80-c432-11e9-93fe-6dfef32f68ee.png)

**Comment by tiny9085** [comment]
it seems CometChatPro-Swift.h's class cannot use in objective-c's project

**Comment by pushpsenairekar2911** [comment]
Hello @tiny9085 , 

We have released a new version for the Objective C Sample app which is built using the CometChat UI Kit. Kindly, check out this one. 
If  you're facing any issues then report it on https://forum.cometchat.com/

Closing this issue because no longer needed.
