### ISSUE TITLE
[SDK-1.8.6] user list callback took a long time,at least 5 seconds

### ISSUE THREAD

**Issue by tiny9085** [cometchat-pro/ios-objective-c-chat-app#3]
[_userRequest fetchNextOnSuccess:^(NSArray<User
contacts) {
       [self.dataArray removeAllObjects];
       if ([contacts count] != 0) {
           [self.dataArray addObjectsFromArray:contacts];
           [self refreshContactsList];
       }else{
           [self refreshContactsList];
       }
   } onError:^(CometChatException * error) {
       [self refreshContactsList];
//        [Alert showAlertForError:error in:self];
   }];

this method success callback took 5-8 seconds, what the problem?

**Comment by pushpsenairekar2911** [comment]
Hello @tiny9085 , 

We have released a new version for the Objective C Sample app which is built using the CometChat UI Kit. Kindly, check out this one. 
If  you're facing any issues then report it on https://forum.cometchat.com/

Closing this issue because no longer needed.
