### ISSUE TITLE
[SDK-2.0.5]ERROR_JSON_EXCEPTION

### ISSUE THREAD

**Issue by Gorilla957** [cometchat-pro/ios-objective-c-chat-app#4]
Error message is "A server with the spectified hostname could not be found."

**Comment by pushpsenairekar2911** [comment]
Hello @Gorilla957 , 

It seems that you haven't added AppId, apiKey and region code in AppConstants.h file. Please, add and run the project, This will resolve your issue. 

if  you're facing any issues then report it on https://forum.cometchat.com/

Closing this issue because no longer needed.
