### ISSUE TITLE
Cannot find protocol declaration for 'CometChatMessageDelegate'

### ISSUE THREAD

**Issue by wolfljj** [cometchat-pro/ios-objective-c-chat-app#5]
xcode 11.3.1
download this sample and changed pod file to 'CometChatPro','2.0.11-Xcode11.3'

build error

Cannot find protocol declaration for 'CometChatGroupDelegate'
Cannot find protocol declaration for 'CometChatMessageDelegate'
Cannot find protocol declaration for 'CometChatUserDelegate'
Cannot find protocol declaration for 'CometChatMessageDelegate'
Cannot find protocol declaration for 'CometChatCallDelegate'

/Downloads/ios-objective-c-chat-app-master/Xcode 11.3/CometChatObjc/main.m:10:9: In file included from /Downloads/ios-objective-c-chat-app-master/Xcode 11.3/CometChatObjc/main.m:10:

/Users//Downloads/ios-objective-c-chat-app-master/Xcode 11.3/CometChatObjc/App/AppDelegate.h:11:9: In file included from /Users//Downloads/ios-objective-c-chat-app-master/Xcode 11.3/CometChatObjc/App/AppDelegate.h:11:

/Users//Downloads/ios-objective-c-chat-app-master/Xcode 11.3/CometChatObjc/App/MainViewController.h:10:9: In file included from /Users//Downloads/ios-objective-c-chat-app-master/Xcode 11.3/CometChatObjc/App/MainViewController.h:10:

how to resolve these

**Comment by pushpsenairekar2911** [comment]
Hello @wolfljj, 

Please run this sample on a physical device. It will resolve your issue.

Thanks.

**Comment by wolfljj** [comment]
I can't build it,how to run on a physical device?

**Comment by wolfljj** [comment]
why close this?

**Comment by pushpsenairekar2911** [comment]
Hello @wolfljj, 

Can you please show us the screenshot of the error you are getting. 
Also, please perform below steps:
1. Clean the project
2. Clear derived data
3. Connect physical device and run the project.

Note: Make sure you’ve selected appropriate Xcode version.

**Comment by pushpsenairekar2911** [comment]
Hello @wolfljj, 

Please, let me know are you able to run the UI Kit project or still facing any issues. We are happy to help.

**Comment by DanBurkhardt** [comment]
I'd like to +1 this-- it is highly disruptive to not be able to run the SDK on the simulator. Running to a device does work, but it cannot run on simulator. 

What's up with that?

**Comment by pushpsenairekar2911** [comment]
Hello @DanBurkhardt and  @wolfljj, 

We have added simulator support for the mixed project from SDK v2.0.13. Please, update your profile to 2.0.13. By doing this you'll ve able to run the project on the simulator as well.
Also, those errors such as `Cannot find protocol declaration for 'CometChatMessageDelegate' will be gone.
